// <auto-generated />
using System;
using DB.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Entities.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nombre = "Drama"
                        },
                        new
                        {
                            GeneroId = 3,
                            Nombre = "Acción"
                        },
                        new
                        {
                            GeneroId = 4,
                            Nombre = "Suspenso"
                        },
                        new
                        {
                            GeneroId = 5,
                            Nombre = "Thriller"
                        },
                        new
                        {
                            GeneroId = 6,
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            GeneroId = 7,
                            Nombre = "Animación"
                        },
                        new
                        {
                            GeneroId = 8,
                            Nombre = "Terror"
                        },
                        new
                        {
                            GeneroId = 9,
                            Nombre = "Aventura"
                        });
                });

            modelBuilder.Entity("DB.Entities.Productora", b =>
                {
                    b.Property<int>("ProductoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoraId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductoraId");

                    b.ToTable("Productora", (string)null);

                    b.HasData(
                        new
                        {
                            ProductoraId = 1,
                            Nombre = "NBC"
                        },
                        new
                        {
                            ProductoraId = 2,
                            Nombre = "HBO"
                        },
                        new
                        {
                            ProductoraId = 3,
                            Nombre = "Netflix"
                        },
                        new
                        {
                            ProductoraId = 4,
                            Nombre = "Fox Television Studio"
                        },
                        new
                        {
                            ProductoraId = 5,
                            Nombre = "Gracie Films"
                        },
                        new
                        {
                            ProductoraId = 6,
                            Nombre = "Nickelodeon"
                        },
                        new
                        {
                            ProductoraId = 7,
                            Nombre = "Incendo Films"
                        },
                        new
                        {
                            ProductoraId = 8,
                            Nombre = "Nova Veranda"
                        },
                        new
                        {
                            ProductoraId = 9,
                            Nombre = "LP Entertainment"
                        },
                        new
                        {
                            ProductoraId = 10,
                            Nombre = "Cartoon Network"
                        },
                        new
                        {
                            ProductoraId = 11,
                            Nombre = "Disney Channel"
                        });
                });

            modelBuilder.Entity("DB.Entities.SerieGenero", b =>
                {
                    b.Property<int>("SerieId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.HasKey("SerieId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("SerieGeneros");
                });

            modelBuilder.Entity("DB.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GeneroPrimarioId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroSecundarioId")
                        .HasColumnType("int");

                    b.Property<string>("LinkYT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Portada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneroPrimarioId");

                    b.HasIndex("GeneroSecundarioId");

                    b.HasIndex("ProductoraId");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneroPrimarioId = 1,
                            GeneroSecundarioId = 2,
                            LinkYT = "https://www.youtube.com/embed/OZL2nwJalQk?si=OS9r2X-RAV3NJQLn&amp;controls=0",
                            Nombre = "The Office",
                            Portada = "/Imagenes/theoffice.jpg",
                            ProductoraId = 1
                        },
                        new
                        {
                            Id = 2,
                            GeneroPrimarioId = 3,
                            GeneroSecundarioId = 6,
                            LinkYT = "https://www.youtube.com/embed/beG07Q917rU?si=T1cmfEp-yqdna5SB",
                            Nombre = "Game of Thrones",
                            Portada = "/Imagenes/got.jpg",
                            ProductoraId = 2
                        },
                        new
                        {
                            Id = 3,
                            GeneroPrimarioId = 5,
                            GeneroSecundarioId = 4,
                            LinkYT = "https://www.youtube.com/embed/yjmDBKyemUw?si=R-3nbfvcVZt9ACWH",
                            Nombre = "Stranger Things",
                            Portada = "/Imagenes/strangerthings.jpg",
                            ProductoraId = 3
                        },
                        new
                        {
                            Id = 4,
                            GeneroPrimarioId = 1,
                            LinkYT = "https://www.youtube.com/embed/l19tQk23noI?si=h5Vin_NgfD_HNPeH",
                            Nombre = "Malcolm In The Middle",
                            Portada = "/Imagenes/malcolm.jpg",
                            ProductoraId = 4
                        },
                        new
                        {
                            Id = 5,
                            GeneroPrimarioId = 1,
                            GeneroSecundarioId = 7,
                            LinkYT = "https://www.youtube.com/embed/F-dNggtr8E0?si=NUxjZp6dKW4u5jil",
                            Nombre = "The Simpsons",
                            Portada = "/Imagenes/simpsons.jpg",
                            ProductoraId = 5
                        },
                        new
                        {
                            Id = 6,
                            GeneroPrimarioId = 2,
                            GeneroSecundarioId = 3,
                            LinkYT = "https://www.youtube.com/embed/kQHo8DU-_Sk?si=fbPPDe6mzC_eJTxh",
                            Nombre = "El Chapo",
                            Portada = "/Imagenes/chapo.jpg",
                            ProductoraId = 3
                        },
                        new
                        {
                            Id = 7,
                            GeneroPrimarioId = 7,
                            GeneroSecundarioId = 6,
                            LinkYT = "https://www.youtube.com/embed/dDhB4_mt2f4?si=5pod83hpdV0bYadx",
                            Nombre = "Winx Club",
                            Portada = "/Imagenes/winx.jpg",
                            ProductoraId = 6
                        },
                        new
                        {
                            Id = 8,
                            GeneroPrimarioId = 8,
                            GeneroSecundarioId = 5,
                            LinkYT = "https://www.youtube.com/embed/_g8E35l0L0w?si=qceFMM7FbR8llu65",
                            Nombre = "The Haunting Hour",
                            Portada = "/Imagenes/hauntinghour.jpg",
                            ProductoraId = 7
                        },
                        new
                        {
                            Id = 9,
                            GeneroPrimarioId = 2,
                            LinkYT = "https://www.youtube.com/embed/6oqiksG962M?si=fhYMXnHbkVHuyU6u",
                            Nombre = "Merlí",
                            Portada = "/Imagenes/merli.jpg",
                            ProductoraId = 8
                        },
                        new
                        {
                            Id = 10,
                            GeneroPrimarioId = 4,
                            GeneroSecundarioId = 7,
                            LinkYT = "https://www.youtube.com/embed/kOKk1wMmZBY?si=OAtXr_WMcJ5G7MzT",
                            Nombre = "Death Note",
                            Portada = "/Imagenes/deathnote.jpg",
                            ProductoraId = 9
                        },
                        new
                        {
                            Id = 11,
                            GeneroPrimarioId = 1,
                            GeneroSecundarioId = 2,
                            LinkYT = "https://www.youtube.com/embed/v4IaSXl-JPw?si=MXZSmrQlF_4adDfl",
                            Nombre = "Scream Queens",
                            Portada = "/Imagenes/screamqueens.jpg",
                            ProductoraId = 4
                        },
                        new
                        {
                            Id = 12,
                            GeneroPrimarioId = 9,
                            GeneroSecundarioId = 7,
                            LinkYT = "https://www.youtube.com/embed/n9Z5dpGuThM?si=4gz0q_1VBhSZ32-T",
                            Nombre = "The Backyardigans",
                            Portada = "/Imagenes/backyardigans.jpg",
                            ProductoraId = 6
                        },
                        new
                        {
                            Id = 13,
                            GeneroPrimarioId = 1,
                            GeneroSecundarioId = 9,
                            LinkYT = "https://www.youtube.com/embed/aOBqbiBDntw?si=x12iU2dMI_kVOPZA",
                            Nombre = "Regular Show",
                            Portada = "/Imagenes/regularshow.jpg",
                            ProductoraId = 10
                        },
                        new
                        {
                            Id = 14,
                            GeneroPrimarioId = 1,
                            GeneroSecundarioId = 9,
                            LinkYT = "https://www.youtube.com/embed/P6EWLTBs-dQ?si=pDYG32N8QvawuOXN",
                            Nombre = "Adventure Time",
                            Portada = "/Imagenes/adventuretime.jpg",
                            ProductoraId = 10
                        },
                        new
                        {
                            Id = 15,
                            GeneroPrimarioId = 2,
                            LinkYT = "https://www.youtube.com/embed/AnAAy91YDy4?si=y9wDI1TCXUfY1WLG",
                            Nombre = "Violetta",
                            Portada = "/Imagenes/violetta.jpg",
                            ProductoraId = 11
                        },
                        new
                        {
                            Id = 16,
                            GeneroPrimarioId = 6,
                            GeneroSecundarioId = 3,
                            LinkYT = "https://www.youtube.com/embed/JAg1XgKEG8U?si=_kwggta2ZGeJP32a",
                            Nombre = "American Dragon Jake",
                            Portada = "/Imagenes/americandragon.jpg",
                            ProductoraId = 11
                        });
                });

            modelBuilder.Entity("DB.Entities.SerieGenero", b =>
                {
                    b.HasOne("DB.Entities.Genero", "Genero")
                        .WithMany("SerieGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DB.Entities.Series", "Series")
                        .WithMany("SerieGeneros")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DB.Entities.Series", b =>
                {
                    b.HasOne("DB.Entities.Genero", "GeneroPrimario")
                        .WithMany()
                        .HasForeignKey("GeneroPrimarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DB.Entities.Genero", "GeneroSecundario")
                        .WithMany()
                        .HasForeignKey("GeneroSecundarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DB.Entities.Productora", "Productora")
                        .WithMany("Series")
                        .HasForeignKey("ProductoraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GeneroPrimario");

                    b.Navigation("GeneroSecundario");

                    b.Navigation("Productora");
                });

            modelBuilder.Entity("DB.Entities.Genero", b =>
                {
                    b.Navigation("SerieGeneros");
                });

            modelBuilder.Entity("DB.Entities.Productora", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("DB.Entities.Series", b =>
                {
                    b.Navigation("SerieGeneros");
                });
#pragma warning restore 612, 618
        }
    }
}
